
################################################################################
# Node-RED Stack or Compose
################################################################################
# #Create data folder
# mkdir node-red
# mkdir node-red/data
# chown -R 1000:1000 node-red/
# #start container
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    #image: nodered/node-red:latest
    build:
      context: ./container
      dockerfile: Dockerfile
    environment:
      - TZ=Europe/Amsterdam
      - PUID=1000
    ports:
      - "18801:1880"
    networks:
      - node-red-net
    volumes:
      - ./node-red/data:/data

networks:
  node-red-net:
